Задание 2. Добавлен README
gpb-it-factory/gladskoy-telegram-bot pull request #2
Opened 2024-05-06 12:26 UTC by saneci

2024-05-07 14:20 UTC, vaganov-vadim requested changes
Привет! Всё круто, мне понравилось твоё README. Давай только на PlantUML-схемку добавим пользователя, важно, что именно он инициирует всё взаимодействие.

2024-05-07 14:20 UTC, vaganov-vadim commented on README.md
> +participant TelegramBot
Давай в схему добавим клиента, чтоб понимать, какую он роль во всей этой схеме играет.

2024-05-08 07:18 UTC, saneci commented on README.md
> +participant TelegramBot
Готово. Плюс добавил пару стилей: изменил отступы блоков participants и выровнял текст над стрелками по центру.

2024-05-13 16:43 UTC, vaganov-vadim approved these changes
Аппрув! Можно фигачить дальше =)

2024-05-13 16:43 UTC, merged