Задание 3. Создан "скелет" бота
gpb-it-factory/gladskoy-telegram-bot pull request #5
Opened 2024-05-14 10:16 UTC by saneci

2024-05-17 05:55 UTC, vaganov-vadim requested changes
У меня в целом вопросов нет, всё круто. Но давай подумаем над необходимостью enum, который я отметил. Вопрос к обсуждению в целом.

2024-05-17 05:55 UTC, vaganov-vadim commented on README.md
> +### Локальный запуск
Лайк, хорошая инструкция.

2024-05-17 05:55 UTC, vaganov-vadim commented on src/main/java/ru/gpbitfactory/minibank/telegrambot/command/Command.java
> +public enum Command {
У меня есть сомнения в необходимости этого enum'а. По сути, его данные используются только в самих командах. Может, тогда эту информацию _инкапуслировать_ в самих командах?

2024-05-17 06:48 UTC, saneci commented on src/main/java/ru/gpbitfactory/minibank/telegrambot/command/Command.java
> +public enum Command {
Уже когда запушил изменения засомневался в правильности этого решения. В общем, ожидал этого замечания :) Согласен, давай тогда уберу это в команды.

2024-05-17 08:10 UTC, saneci commented on src/main/java/ru/gpbitfactory/minibank/telegrambot/command/Command.java
> +public enum Command {
Внёс [исправления ](https://github.com/gpb-it-factory/gladskoy-telegram-bot/pull/5/commits/ae255ed3ac3b4ee1fa3357fff1cd17fd0e720eff), надеюсь там можно было просто передать значения в конструктор)

2024-05-20 13:31 UTC, vaganov-vadim approved these changes

2024-05-20 13:31 UTC, merged